# Generated by Django 4.0 on 2022-05-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
