# Generated by Django 4.0 on 2022-07-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='text')),
                ('total', models.IntegerField()),
                ('checking', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.checking')),
            ],
        ),
    ]
