# Generated by Django 4.0 on 2022-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(null=True, to='products.Category'),
        ),
    ]
