# Generated by Django 4.0 on 2022-01-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('products', '0002_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='publication.publication'),
        ),
    ]
