# Generated by Django 4.0 on 2022-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_attributevalue_product_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='atribute_values',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='product_variant',
            field=models.ManyToManyField(blank=True, related_name='attr_values', to='products.ProductVariant'),
        ),
    ]
