# Generated by Django 4.0 on 2022-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdouct',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
