# Generated by Django 4.0 on 2022-05-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_prdouct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdouct',
            new_name='prdouct_color',
        ),
    ]
