# Generated by Django 4.0 on 2022-05-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_category_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
